---
title: "Figure 6 Vignette"
author: "Jianhong Ou"
vignette: >
  %\VignetteIndexEntry{Figure 6 Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
  html_document:
  theme: simplex
  toc: true
  toc_float: true
  toc_depth: 4
  fig_caption: true
---

```{r setup, include=FALSE}
suppressPackageStartupMessages({
  library(geomeTriD)
  library(geomeTriD.documentation)
  library(GenomicRanges)
  library(GenomeInfoDb)
  library(trackViewer)
  library(InteractionSet)
})
knitr::opts_chunk$set(echo = TRUE, out.width = "900px")
options(rgl.useNULL = TRUE)
```

# Figure 5

The Figure 5 is the showcase for `geomeTriD` package to validate the prediction of 3D structures.

## Load Libraries

```{r loadLibrary}
library(geomeTriD)
library(geomeTriD.documentation)
library(GenomicRanges)
library(GenomeInfoDb)
library(trackViewer)
library(InteractionSet)
```

## Load data and annotations

```{r}
# original interaction map vs. spatialDistanceHeatmap

gr <- GRanges('chrX:1-20000000')
## load FLAMINGO results
FLAMINGO_chrX_5kb <- importFLAMINGO('https://github.com/wangjr03/FLAMINGO/raw/refs/heads/main/predictions/GM12878/chrX_5kb.txt')[[1]]
sdm_FLAMINGO <- spatialDistanceMatrix(subsetByOverlaps(FLAMINGO_chrX_5kb, gr), fill_NA = TRUE)

## load SuperRec results
extdata <- system.file('extdata', 'GSE63525', package = 'geomeTriD.documentation')
superRec_chrX_5kb <- importSuperRec(file.path(extdata, 'combined_30.chrX.SuperRec.txt.gz'),
                                    ## this file is not the real input file SuperRec
                                    ## the file is reduced size to construct the xyz object for this doc. 
                                    file.path(extdata, 'combined_30.chrX.SuperRec.input.subset.gz'),
                                    binsize = 5000, chr='chrX')[[1]]
sdm_superRec<- spatialDistanceMatrix(subsetByOverlaps(superRec_chrX_5kb, gr), fill_NA = TRUE)

## load hic signal matrix
hic_sig <- importGInteractions('https://ftp.ncbi.nlm.nih.gov/geo/series/GSE63nnn/GSE63525/suppl/GSE63525%5FGM12878%5Fdilution%5Fcombined%5F30.hic',
                               format = 'hic', ranges = GRanges('X:1-20000000'),
                               resolution = 250000, out='GInteractions')
seqlevelsStyle(regions(hic_sig)) <- 'UCSC'
anchors <- anchorIds(hic_sig)
rg <- range(regions(hic_sig))
w <- unique(width(regions(hic_sig)))
gr <- slidingWindows(rg, width = w, step = w)[[1]]
df <- data.frame(i=anchors[[1]], j=anchors[[2]], score=log10(mcols(hic_sig)$score))
m <- xtabs(score ~ i + j, data = df)
m <- m+t(m)
## function to increase the contrasts
sigmoid_transform <- function(mat, center_value, steepness){
  1 / (1 + exp(-steepness * (m - center_value)))
}
mat_sigmoid <- sigmoid_transform(m, center_value = mean(m, na.rm=TRUE), steepness = 5)
par("mfcol"=c(1, 2))
image(mat_sigmoid, useRaster=TRUE, col = rev(hcl.colors(n=12, "OrRd")))
image(sdm_FLAMINGO, useRaster = TRUE, col = hcl.colors(n=12, "OrRd"))

## check Distance-Contact correlation
safe_scale <- function(x) {
  rng <- range(x, na.rm = TRUE)
  if (diff(rng) == 0) return(x)
  (x - rng[1]) / diff(rng)
}
sdm_80 <- function(x){
  sdm_80 <- rowsum(x, rep(seq.int(80), each=50)[seq.int(nrow(x))])
  sdm_80 <- rowsum(t(sdm_80), rep(seq.int(80), each=50)[seq.int(ncol(sdm_80))])
  sdm_80 <- t(sdm_80)
  sdm_scaled_safe <- safe_scale(sdm_80)
}

mat_scaled_safe <- safe_scale(m)
sdm_80_FLAMINGO <- sdm_80(sdm_FLAMINGO)
sdm_80_superRec <- sdm_80(sdm_superRec)

(cor_FLAMINGO <- cor.test(as.numeric(mat_scaled_safe), 
                     as.numeric(1/sdm_80_FLAMINGO), method = 'spearman'))
(cor_superRec <- cor.test(as.numeric(mat_scaled_safe), 
                     as.numeric(1/sdm_80_superRec), method = 'spearman'))

## check Reconstruction Error
re <- function(d_model, hic_sig){
  sum(hic_sig*(d_model - 1/hic_sig)^2, na.rm = TRUE)
}

re(sdm_80_FLAMINGO, mat_scaled_safe)
re(sdm_80_superRec, mat_scaled_safe)
```


## SessionInfo

```{r sessionInfo}
sessionInfo()
```